### ISSUE TITLE
Add a "Visits" column to all function lists

### ISSUE THREAD

**Issue by maks-a** [VerySleepy/verysleepy#23]
For the call stack and callers view, 'Visits' specifies the number of entries to a given function.

It may help to profile functions with the same exclusive/inclusive time, but different entries number.

**Comment by CyberShadow** [comment]
Very Sleepy is a polling profiler, which means that it does not know how many times a function was called. Instead, it samples the program at equal time intervals, and thus counts samples.

Because it samples programs at equal time intervals, the number of samples is always directly proportional to the % of time displayed.
