### ISSUE TITLE
What about Very Sleepy's Windows 10 compatibility?

### ISSUE THREAD

**Issue by scampsd** [VerySleepy/verysleepy#33]
Good afternoon,
I've been working with Very Sleepy before, while my computer was still a Windows 7 one, and I had the impression that the tool was working fine.

Now I'm faced with quite some instabilities:
1) When I run the application, there is an application which is not visible in the list of processes. In order to get it working, I need to re-install it and choose to start the application at the end of the installation.
2) Once the profiled application is stopped, I stop the profiling, and then I see the "dialog box" "Waiting for symbol query to start ...", but this dialog box doesn't stop. In the code snippet I've seen that the display of this dialog box is implemented using a "while(true)" loop. Maybe it's a good idea to use a timer for this feature. In case of a time-out another dialog can be shown, mentioning what to do in order not to stay blocked.

Best regards
Dominique Descamps

**Comment by CyberShadow** [comment]
Sorry for the late reply; somehow I had not noticed this message when you posted it.

> When I run the application, there is an application which is not visible in the list of processes. In order to get it working, I need to re-install it and choose to start the application at the end of the installation.

If you need to profile an application that is running with elevated privileges, you need to run Very Sleepy itself elevated as well - i.e. right-click the Very Sleepy shortcut, and select "Run as Administrator".

> Once the profiled application is stopped, I stop the profiling, and then I see the "dialog box" "Waiting for symbol query to start ...", but this dialog box doesn't stop. In the code snippet I've seen that the display of this dialog box is implemented using a "while(true)" loop. Maybe it's a good idea to use a timer for this feature. In case of a time-out another dialog can be shown, mentioning what to do in order not to stay blocked.

It is difficult to tell what the problem is just from your description; it would help to get a stack trace of the symbol query thread to know where it gets stuck. I would guess that it would almost surely be in some DbgHelp call - in which case there is no safe way to abort such a call (other than letting it continue in the background). However, without symbol information, the profiling results will almost always be useless (displaying offsets instead of function names), so I think the only actionable here would be to identify and fix the underlying cause of the symbol resolution getting stuck.

If you haven't already done so, I would suggest trying to build Very Sleepy from source code, as it has a number of fixes that are not yet included in an official release.

**Comment by CyberShadow** [comment]
Could you please see if this issue occurs with the latest release:
https://github.com/VerySleepy/verysleepy/releases

As the latest release includes many fixes, it's likely that this particular problem was fixed as well. If you encounter further problems, please leave a comment or open a new issue. Thanks!
