### ISSUE TITLE
Investigate CMake build support

### ISSUE THREAD

**Issue by 8BitPimp** [VerySleepy/verysleepy#36]
It may be of use to add CMake build support.

This would allow all versions of VisualStudio+MinGW to be compiled for, rather then having a single (older) checked in visual studio solution.  CMake is not perfect by any means but it may be of use in this situation, and could live along side the visual studio solution for some time.

Thoughts?

**Comment by CyberShadow** [comment]
I think switching to CMake would make sense if:

1. It made the build process simpler, e.g. by taking care of building wxWidgets and the debug helpers. Simply replacing the Visual Studio solutions with a CMakeLists file makes the build process one step more complicated and introduces an additional dependency, which by itself is difficult to justify.
2. Someone contributed a CMakeLists file, as I'm not sufficiently proficient with CMake to confidently write one.

**Comment by CyberShadow** [comment]
I had a go at this today, and ran into the following issues:

1. Even though CMake includes a module which allows using a built wxWidgets installation in a project, there is no simple way to build wxWidgets itself from within CMake. This means that users will still need to install and manually build wxWidgets before they can build Very Sleepy, and in fact do this four times if they want to build all Debug/Release Win32/x64 combinations.

2. It doesn't seem possible to do both a 32-bit and 64-bit build from inside CMake, because CMake exposes 64-bit Visual Studio builds as a separate generator. This means that to build both a 32-bit and 64-bit version of Very Sleepy (and both need to be built to build a full installer, as profiling 32-bit processes requires using a 32-bit version of Very Sleepy), the user will need two `cmake` invocations from two build directories to perform this successfully. This is a step backwards from the current situation, where the same Visual Studio project file contains both target platforms. This issue also prohibits building an installer from the same CMakeLists file, which would have been a big point in justifying the switch to CMake.

As I don't see a way forward with these issues, I am closing this issue for now.

**Comment by CyberShadow** [comment]
FWIW: See #40, which greatly improves the build process. Hopefully that should resolve most of the pain points of building Very Sleepy.
