### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by doginthenight** [VerySleepy/verysleepy#49]
Why has there been no release for more than 2 years?
While I can find much praise for Very Sleepy online, the one reoccurring complaint I find is related to resolving symbols. I noticed that significant improvements have been made on this front and am wondering why people have to go through the effort of compiling to get these features.
Thanks!

**Comment by galkinvv** [comment]
I've used latest appveyor artifacts for installing them on several machines. But now appveyor deleted latest artifacts (after 6months after building last commit) - see  https://ci.appveyor.com/project/CyberShadow/verysleepy/build/artifacts 

From my practice the current master is stable & usable enough to be published as a release or at least as a snapshot.
Actually VerySleepy is the **only** prfiler that I'm not afraid installing on production servers, since it doesn't affect any system state. A great tool!

**Comment by rmitton** [comment]
I've pushed a new build to AppVeyor. Please bear in mind Very Sleepy is very much in maintenance mode unless someone wants to step up and take charge of it.

**Comment by Calinou** [comment]
The AppVeyor build isn't available anymore since the last commit is more than 6 months old. Could you push a trivial commit (such as updating copyright years) to make a new build available? Thanks in advance :slightly_smiling_face:

**Comment by rmitton** [comment]
I kicked off a new build but unfortunately it's getting an error due to SSL permissions(?) from sourceforge.

I'm afraid I no longer have time to work on Sleepy to fix these things. Maintainers welcome :/

**Comment by CyberShadow** [comment]
Done! 52bf620fd96f5b4941812a83064f0887d62399b6

**Comment by CyberShadow** [comment]
It looks like SourceForge forgot to renew their SSL certificate, or something went wrong with their auto-renewal process.

Hopefully, they will notice / someone will tell them, and this will be resolved in a few days.

**Comment by CyberShadow** [comment]
Looks like the issue was indeed resolved, so a build should be available as soon as the CI build completes:
https://ci.appveyor.com/project/CyberShadow/verysleepy

**Comment by galkinvv** [comment]
since there is no active development now, but te changes from 2014 prerelease are great (and are available from appveyour from time to time) - I suppose that fixing current binaries as another official alpha pre-release would be useful.

P.S. I already made a fork in my account just to save just-recompiled official appveyor artifacts in releases there. Not giving direct link, so that every downloader undestand that binaries are bublished not by a offcial devs, but by untrusted 3rd-party  person - me)))

**Comment by CyberShadow** [comment]
After quite a few misadventures I got my code signing to work again, so I published v0.91:
https://github.com/VerySleepy/verysleepy/releases/tag/v0.91

I also added a deploy configuration to AppVeyor to push the artifacts to a GitHub release:
https://github.com/VerySleepy/verysleepy/releases/tag/appveyor

Hopefully that should fix the issue of expiring artifacts with development builds going forward.

@rmitton If you are still maintaining your website, then that should probably be updated to reflect the latest version.

**Comment by rmitton** [comment]
Thanks!
I have updated my website with a link to the new release.
