### ISSUE TITLE
mingw-w64 compiled executables' symbols not recognized

### ISSUE THREAD

**Issue by Kotauskas** [VerySleepy/verysleepy#66]
The title says it all. I built an executable with `mingw-w64` (latest official, G++ 8.1.0), of course with the `-g` flag, and it shows just addresses, not actual function names (and doesn't display code).

**Comment by CyberShadow** [comment]
Does it work with the latest Dr. MinGW? ([download](https://github.com/jrfonseca/drmingw/releases) and unpack `mgwhelp.dll` over `dbghelpdr.dll`).

**Comment by Kotauskas** [comment]
There's no `dbghelpdr.dll` file in the Very Sleepy installation directory.

**Comment by CyberShadow** [comment]
I'm assuming you are using the latest release from the website. Please update to the latest development version as described in this repository's README first.

**Comment by Kotauskas** [comment]
No, still doesn't recognize (latest development snapshot, `-g` 64-bit `mingw-w64` executable, latest Dr. MinGW): ![image](https://user-images.githubusercontent.com/28248600/58954512-0df32100-87a2-11e9-8ce8-d0c71da32fca.png)

**Comment by CyberShadow** [comment]
Does it work if you rebuild the program with `-gdwarf-3` or `-gdwarf-2` ?

**Comment by Kotauskas** [comment]
No, `ld` doesn't know what's a `-gdwarf-3`:
`ld.exe: cannot open output file build\output\exe\windows\x86_64\Debug\GemVerse.exe: Invalid argument
collect2.exe: error: ld returned 1 exit status`. Maybe that's because I have a `seh` GCC (64-bit doesn't have `dwarf`)

**Comment by CyberShadow** [comment]
That would be a compiler switch, not linker. Debug information is emitted by the compiler and placed in object files during compilation. The linker merely puts it together.

**Comment by Kotauskas** [comment]
No, my command line is `x86_64-w64-mingw32-g++.exe %INCLUDEDIRS% %LIBDIRS64% %CFLAGS% %OBJECTS64% %SOURCES% %LIBS% -o build\output\exe\windows\x86_64\Debug\GemVerse.exe` where `%CFLAGS%` contains `-gdwarf-3`

**Comment by Kotauskas** [comment]
Same for `-gdwarf-2`

**Comment by CyberShadow** [comment]
The error message you posted above really doesn't look like it's due to the debug information format. Is it possible that's due to an unrelated error with your build? Is the source code (or at least build script / Makefiles) available?

**Comment by Kotauskas** [comment]
My project builds almost fine, except for errors in `fstream` and `fs_path.h` (errors in compiler headers, what?), but that's out of this ticket's scope.

**Comment by CyberShadow** [comment]
If you can't post the code, then I don't think I can help you until you figure out why your toolchain is producing a weird error given `-gdwarf-2`.

**Comment by Kotauskas** [comment]
I removed the part that invokes `fsteam` stuff and now I'm getting multiple definition errors, I'll write back when I fix that.

**Comment by Kotauskas** [comment]
So, I decided to test the weird behavior with some simple code:
![image](https://user-images.githubusercontent.com/28248600/59225660-fb317f80-8bd9-11e9-86b2-bf1501e25201.png)
As you can see, the source code correctly shows up and symbols are recognized. To achieve this, I separated compiling and linking, as if I did an incremental build, and passed `-gdwarf-3` to the compilaton step invocation of `g++`, so my compilation steps were:
```
PS> g++ -c main.cpp -o main.o -gdwarf-3
PS> g++ main.o -o main.exe
```

**Comment by Kotauskas** [comment]
Resolution:

1. Update Very Sleepy to 0.91+
2. Download [latest Dr. MinGW](https://github.com/jrfonseca/drmingw/releases), unpack `mgwhelp.dll` and replace `dbghelpdr.dll` from Very Sleepy's files with it
3. Compile executable with `-gdwarf-3` and link separately without that flag

**Comment by CyberShadow** [comment]
If it works with `-gdwarf-3`, then the problem is not within Very Sleepy.

I don't know what position Dr.MinGW has regarding supporting newer DWARF versions. You may want to follow up there.

If Dr.MinGW does not intend to support newer DWARF versions, then we should document compiling with `-gdwarf-3` in this project somewhere too.

**Comment by DEF7** [comment]
I've had this problem for years, but it's random. Including -gdwarf-3 and replacing the Dr.MinGW DLL doesn't change anything at all. What could the problem be?

![image](https://github.com/user-attachments/assets/a120c211-b76f-4afb-9a81-3353d6059677)

gdb/gprof works fine, and VerySleepy has always worked fine with 32-bit executables, and is hugely preferable to gdb/gprof but it's really hit-and-miss with VerySleepy working with different projects. I compile and link everything using the same flags between projects and all I can think is that it's confusing different binaries within a single process.

For example, here's a little VulkanTest program I made to learn the Vulkan API, and it's somehow able to find the debug symbols and show me source files/lines/etc:

![image](https://github.com/user-attachments/assets/3a689436-7d8c-43e1-8329-65eb174f3642)

...but this was the console output about VulkanTest after selecting it, before profiling it for 2 seconds:


```
DBGHELP: Symbol Search Path: ;C:\Users\charlie\Dropbox\Projects\CONCEPTS\VulkanTest;SRV*D:\Users\Daddio\AppData\Local\sleepy
DBGHELP: No debug info for C:\Users\charlie\Dropbox\Projects\CONCEPTS\VulkanTest\VulkanTest.exe.  Searching for dbg file
DBGHELP: C:\Users\charlie\Dropbox\Projects\CONCEPTS\VulkanTest\VulkanTest.dbg - file not found
DBGHELP: C:\Users\charlie\Dropbox\Projects\CONCEPTS\VulkanTest\exe\VulkanTest.dbg - path not found
DBGHELP: C:\Users\charlie\Dropbox\Projects\CONCEPTS\VulkanTest\symbols\exe\VulkanTest.dbg - path not found
DBGHELP: C:\Users\charlie\Dropbox\Projects\CONCEPTS\VulkanTest\VulkanTest.dbg - file not found
DBGHELP: C:\Users\charlie\Dropbox\Projects\CONCEPTS\VulkanTest\exe\VulkanTest.dbg - path not found
DBGHELP: C:\Users\charlie\Dropbox\Projects\CONCEPTS\VulkanTest\symbols\exe\VulkanTest.dbg - path not found
DBGHELP: C:\Users\charlie\Dropbox\Projects\CONCEPTS\VulkanTest\VulkanTest.dbg - file not found
DBGHELP: C:\Users\charlie\Dropbox\Projects\CONCEPTS\VulkanTest\VulkanTest.exe missing debug info.  Searching for pdb anyway
DBGHELP: C:\Users\charlie\Dropbox\Projects\CONCEPTS\VulkanTest\VulkanTest.pdb - file not found
DBGHELP: C:\Users\charlie\Dropbox\Projects\CONCEPTS\VulkanTest\exe\VulkanTest.pdb - file not found
DBGHELP: C:\Users\charlie\Dropbox\Projects\CONCEPTS\VulkanTest\symbols\exe\VulkanTest.pdb - file not found
DBGHELP: Can't use symbol server for VulkanTest.pdb - no header information available
DBGHELP: VulkanTest.pdb - file not found
DBGHELP: VulkanTest - no symbols loaded
...
(...searches for symbols in loaded DLLs in the process...)
...
DBGHELP: MOD: MSVCP90
DBGHELP: MOD: graphics-hook64
DBGHELP: MOD: DEVOBJ
DBGHELP: MOD: WINTRUST
DBGHELP: MOD: atig6pxx
DBGHELP: MOD: OPENGL32
DBGHELP: MOD: GLU32
DBGHELP: No debug info for C:\Users\charlie\Dropbox\Projects\CONCEPTS\VulkanTest\VulkanTest.exe.  Searching for dbg file
DBGHELP: symsrv.dll load failure
DBGHELP: C:\Users\charlie\Dropbox\Projects\CONCEPTS\VulkanTest\VulkanTest.dbg - file not found
DBGHELP: C:\Users\charlie\Dropbox\Projects\CONCEPTS\VulkanTest\exe\VulkanTest.dbg - path not found
DBGHELP: C:\Users\charlie\Dropbox\Projects\CONCEPTS\VulkanTest\symbols\exe\VulkanTest.dbg - path not found
DBGHELP: C:\Users\charlie\Dropbox\Projects\CONCEPTS\VulkanTest\VulkanTest.dbg - file not found
DBGHELP: C:\Users\charlie\Dropbox\Projects\CONCEPTS\VulkanTest\VulkanTest.exe missing debug info.  Searching for pdb anyway
DBGHELP: VulkanTest.pdb - file not found
DBGHELP: VulkanTest - no symbols loaded
DBGHELP: profapi.pdb - file not found
DBGHELP: profapi - no symbols loaded

Finished.
```

It starts with looking for debug symbols for the EXE, fails, then deals with all the loaded DLLs, and then re-attempts to load symbols for the EXE itself, and never succeeds. Yet when I profile it the thing acts like it did find debug symbols because it's aware of source files/lines/funcs. Why did it say it didn't find debug symbols? This is *clearly* a problem with VerySleepy itself because it's saying it never found symbols and yet behaves like it did.

What's the "symserv.dll load failure" mean? Could that be a clue?

Something is clearly wrong here and it's hard to believe that all these years later it's never been figured out or fixed or anything.
